<?php
/*
  This file contains the database credentials.
  This file exists so that people downloading the project KNOW they must have this file.
  These credentials are in a separate file so that they are less likely to be committed since the file will always be modified.
*/

// Replace "REPLACE" with the correct values for your database.
$gMysqlServer = "REPLACE";
$gMysqlDb = "REPLACE";
$gMysqlUsername = "REPLACE";
$gMysqlPassword = "REPLACE";

?>
